// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRkZG6p6VYWsw5j2UDSWK1NqDbAomVcoU',
    appId: '1:429066132118:web:24d7d6d7afc1007c6a80b7',
    messagingSenderId: '429066132118',
    projectId: 'pandas-2a919',
    authDomain: 'pandas-2a919.firebaseapp.com',
    storageBucket: 'pandas-2a919.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuWFVZlsc3ZXodchoKIihXavy0l-Mkuc4',
    appId: '1:429066132118:android:91afba5cacdc1ec16a80b7',
    messagingSenderId: '429066132118',
    projectId: 'pandas-2a919',
    storageBucket: 'pandas-2a919.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHKEsT0flOLk_iddFYCoW67Z7zS5c15c8',
    appId: '1:429066132118:ios:de1ea9a784b4f2c96a80b7',
    messagingSenderId: '429066132118',
    projectId: 'pandas-2a919',
    storageBucket: 'pandas-2a919.appspot.com',
    androidClientId: '429066132118-3gk7d7uiec51tm6emdmokhmaeh8p1dq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pandas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHKEsT0flOLk_iddFYCoW67Z7zS5c15c8',
    appId: '1:429066132118:ios:e613e299ab5eaae86a80b7',
    messagingSenderId: '429066132118',
    projectId: 'pandas-2a919',
    storageBucket: 'pandas-2a919.appspot.com',
    androidClientId: '429066132118-3gk7d7uiec51tm6emdmokhmaeh8p1dq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pandas.RunnerTests',
  );
}
